import Project.Dilatation.Multicenter
import Mathlib.Data.Sum.Basic
import Project.Dilatation.ReesAlgebra
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.DirectSum.Basic
import Project.Dilatation.lemma
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Localization.Basic
import Project.Dilatation.Family
import Mathlib.RingTheory.GradedAlgebra.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import Project.HomogeneousSubmonoid.Basic
import Project.ForMathlib.TensorProduct
import Project.Proj.Over
import Project.Dilatation.Multicenter


suppress_compilation
universe u
variable {A : Type u} [CommRing A]
variable {ι : Type u} [Fintype ι] (L : ι → Ideal A)
[DecidableEq ι]
variable [(i : ι →₀ ℤ) → Decidable (i ∈ Set.range (ρNatToInt ι))]


open GoodPotionIngredient
def Bl  := Proj
  (τ := GoodPotionIngredient (gradingOfInjection (ReesAlgebra.grading L)
    (ρNatToInt ι)) ) id


structure Mu where
multicenter: Multicenter A
Ψ : multicenter.index → ι
surj : Function.Surjective Ψ
cond : ∀ i, multicenter.LargeIdeal i = L (Ψ i)




def union_center (F F': Multicenter A): Multicenter A :=
  { index := F.index ⊕ F'.index
    ideal := fun i => match i with
      | Sum.inl i => F.LargeIdeal i
      | Sum.inr i => F'.LargeIdeal i
    elem := fun i => match i with
      | Sum.inl i => F.elem i
      | Sum.inr i => F'.elem i
    }

def union_Mu (P P' : Mu L) : Mu L :=
  { multicenter := union_center P.multicenter P'.multicenter,
    Ψ := Sum.map (P.Ψ) (P'.Ψ),
    surj := by
      apply Function.Surjective.sum_map
       sorry
    cond := by
          sorry }




lemma Mu_rel (P: Mu L) :
 Homogeneous subset gen by  {.of _ e_i P.multicenter.elem  i |i : P.multicenter.index}
     is (i : ι →₀ ℤ)-relevant in ReesAlgebra L  := by
     P.multicenter.elem i belongs to L Ψ i and has degree e_i. Use that Ψ is surjective.
     The group generated by the e_i is (i : ι →₀ ℤ)
     sorry



def Mu_mor (P: Mu L):
  A[P.multicenter] →ₐ[A] Potion {.of _ e_i P.multicenter.elem  i |i : P.multicenter.index} ReesAlgebra L := by
   desc F.Multicenter
    (by
     -- apply that s is nonzero in Potion (A,S)
     )
    (by
      let i ∈ F.index
      Then (a) ⊆ (L_i) is trivial, so same holds for image
      Reciprocally, we write m=m/a .a.
      )

lemma Mu_mor_iso (P: Mu L ): Mu_mor is an iso :=
  by  injective surjective
   sorry


 sorry


def Po (P: Mu) : open subscheme of Bl :=
    Spec(Potion P in Rees)

lemma inter_Po (P,P' : Mu L) : Po.P ∩ Po.P' = Po.union.Mu P P' (as open subschemes) := by
   many already stasblished lemmas
   sorry



lemma Dila_cov_proj : ∪ (F: Mu) dila F
                     = Bl L A :=
     --in the paper
    sorry


--lemma 2 in draft


lemma ProjBlowup_UnivProp_unicity_affine : [Scheme T Spec(A)]
(φ φ': T → ProjBlowup_def_affine A L over Spec(A)): φ=φ' := by
  Let x ∈ T.
  Reduce to local neighborhood
  put y=φx
  put y'=φ'x
  obtain P ∈ Mu L such that y ∈ Mu P
  obtain p' ∈ Mu L such that y ∈ Mu P'
  Let U=Spec(B) be an affine neighborhood of x in φ^-1 (Po P) ∩ φ'^-1 (Po P').
  consider the restrictions of φ and φ' to U
  Phi factors through Po P, Phi' factors through Po P'
  apply lemma 2
  apply univ prop of dilatations
  sorry

/-obtain ⟨j, x, rfl⟩ := (glueData ℱ).ι_jointly_surjective x
  obtain ⟨j', x', rfl⟩ := (glueData ℱ).ι_jointly_surjective x'-/
