import Project.Dilatation.Multicenter
import Mathlib.Data.Sum.Basic
import Project.Dilatation.ReesAlgebra
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.DirectSum.Basic
import Project.Dilatation.lemma
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Localization.Basic
import Project.Dilatation.Family
import Mathlib.RingTheory.GradedAlgebra.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import Project.HomogeneousSubmonoid.Basic
import Project.ForMathlib.TensorProduct
import Project.Proj.Over
import Project.Dilatation.Multicenter



suppress_compilation
universe u
variable {A : Type u} [CommRing A]
variable {B : Type u} [CommRing B]
variable {ι : Type u} [Fintype ι] (L : ι → Ideal A)
[DecidableEq ι]
variable [(i : ι →₀ ℤ) → Decidable (i ∈ Set.range (ρNatToInt ι))]


open GoodPotionIngredient
def Bl  := Proj (τ := GoodPotionIngredient (ReesAlgebra.intGrading L)) id


structure Mu where
multicenter: Multicenter A
Ψ : multicenter.index → ι
sec : ι → multicenter.index
surj : ∀ i, Ψ (sec i) = i
cond : ∀ i, multicenter.LargeIdeal i = L (Ψ i)



@[simps]
def union_center (F F': Multicenter A): Multicenter A :=
  { index := F.index ⊕ F'.index
    ideal := fun i => match i with
      | Sum.inl i => F.ideal i
      | Sum.inr i => F'.ideal i
    elem := fun i => match i with
      | Sum.inl i => F.elem i
      | Sum.inr i => F'.elem i
    }
@[simp]
lemma union_center_largeIdeal_left (F F' : Multicenter A) (i : F.index) :
 (union_center F F').LargeIdeal (Sum.inl i) = F.LargeIdeal i := rfl

@[simp]
lemma union_center_largeIdeal_right (F F' : Multicenter A) (i : F'.index) :
 (union_center F F').LargeIdeal (Sum.inr i) = F'.LargeIdeal i := rfl

def union_Mu (P P' : Mu L) : Mu L :=
  { multicenter := union_center P.multicenter P'.multicenter,
    Ψ := Sum.rec (P.Ψ) (P'.Ψ),
    sec := Sum.inl ∘ P.sec
    surj := by
      intro i
      simpa [union_center_index, Function.comp_apply] using P.surj i
    cond := by
      rintro (i|i)
      · simp [P.cond i]
      · simp [P'.cond i] }

def clo_mu (P: Mu L) [DecidableEq P.multicenter.index] :
    HomogeneousSubmonoid (ReesAlgebra.intGrading L):=
  HomogeneousSubmonoid.closure
      { ReesAlgebra.single L (Finsupp.single (P.Ψ i) 1) ⟨P.multicenter.elem i, by
        rw [familyPow_single, ← P.cond i]
        apply Multicenter.elem_mem_LargeIdeal⟩ | (i : P.multicenter.index) } <| by
  rintro _ ⟨i, rfl⟩
  use (Finsupp.single (P.Ψ i) 1)
  simp only [ReesAlgebra.intGrading, gradingOfInjection, Set.mem_range, ρNatToInt_apply]
  split_ifs with h
  · rcases h with ⟨n, hn⟩
    have eq₀ : n = Finsupp.single (P.Ψ i) 1 := by
      ext j
      rw [Finsupp.ext_iff] at hn
      specialize hn j
      simp only [Finsupp.single_apply] at hn ⊢
      split_ifs at hn ⊢ with h
      · simpa [ρNatToInt] using hn
      · simpa [ρNatToInt] using hn

    refine ⟨⟨P.multicenter.elem i, ?_⟩, ?_⟩
    · simp_rw [← hn]
      generalize_proofs _ h1
      have eq : Set.rangeSplitting ⇑(ρNatToInt ι) ⟨(ρNatToInt ι) n, h1⟩ = n := by
        apply ρNatToInt_inj
        rw [Set.apply_rangeSplitting (ρNatToInt ι)]
      rw [eq, eq₀]

      rw [familyPow_single, ← P.cond i]
      apply Multicenter.elem_mem_LargeIdeal

    · apply ReesAlgebra.single_eq
      subst eq₀
      apply ρNatToInt_inj
      simp_rw [← hn]
      rw [Set.apply_rangeSplitting (ρNatToInt ι)]
  · refine h ?_ |>.elim
    use Finsupp.single (P.Ψ i) 1
    ext j
    simp [ρNatToInt]


lemma Mu_rel (P: Mu L) [DecidableEq P.multicenter.index]  : (clo_mu L P).IsRelevant := by
  rw [HomogeneousSubmonoid.isRelevant_iff_finiteIndex_of_FG]
    --  P.multicenter.elem i belongs to L Ψ i and has degree e_i. Use that Ψ is surjective.
    --  The group generated by the e_i is (i : ι →₀ ℤ)
  sorry

-- A -> (Rees L)[0] -> (clo_mu L P).Potion
def mu_potion_algebraMap (P: Mu L) [DecidableEq P.multicenter.index] :
    A →+* ((clo_mu L P).Potion) :=
  RingHom.comp (algebraMap _ _) (ReesAlgebra.degreeZeroIso' L |>.toRingHom)


instance (P: Mu L) [DecidableEq P.multicenter.index] : Algebra A ((clo_mu L P).Potion) :=
  RingHom.toAlgebra (mu_potion_algebraMap L P)

omit [Fintype ι] in
lemma mu_potion_algebraMap_eq (P: Mu L) [DecidableEq P.multicenter.index] :
  algebraMap A (clo_mu L P).Potion = mu_potion_algebraMap L P := rfl

open Family
lemma mu_potion_algebraMap_eq_sq_over_self (P: Mu L) [DecidableEq P.multicenter.index] (i) :
  (algebraMap A (clo_mu L P).Potion (P.multicenter.elem i)) =
  (HomogeneousLocalization.mk
    { deg := ρNatToInt _ <| Finsupp.single (P.Ψ i) 1,
      num := ⟨ReesAlgebra.single _ (Finsupp.single (P.Ψ i) 1) ⟨(P.multicenter.elem i)^2, by
        rw [familyPow_single, ← P.cond]
        apply Ideal.pow_mem_of_mem
        apply Multicenter.elem_mem_LargeIdeal
        norm_num⟩, ReesAlgebra.single_has_degree' ..⟩
      den := ⟨ReesAlgebra.single _ (Finsupp.single (P.Ψ i) 1) ⟨(P.multicenter.elem i), by
        rw [familyPow_single, ← P.cond]
        apply Multicenter.elem_mem_LargeIdeal⟩, ReesAlgebra.single_has_degree' ..⟩
      den_mem := by
        refine Submonoid.subset_closure ?_
        use i } : (clo_mu L P).Potion) := sorry

/-

(ReesAlgebra.single L (Finsupp.single (P.Ψ i) 1))
  ⟨a², ⋯⟩ ≠
((ReesAlgebra.single L (Finsupp.single (P.Ψ i) 1))
  ⟨a, ⋯⟩)²
-/
open Multicenter Multicenter.Dilatation
def Mu_mor (P: Mu L) [DecidableEq P.multicenter.index] :
  A[P.multicenter] →ₐ[A] (clo_mu L P).Potion :=
   Multicenter.desc P.multicenter
    (by
      intro i
      rw [mu_potion_algebraMap_eq_sq_over_self]
      intro x
      rw[]
      -- Add a meaningful rewrite here or remove this line if unnecessary

      --simp only [mu_potion_algebraMap_eq, mu_potion_algebraMap, RingEquiv.toRingHom_eq_coe,
      --refine Submonoid.subset_closure ?_]
      --simp only [RingEquiv.toEquiv_eq_coe, EquivLike.coe_coe, ReesAlgebra.degreeZeroIso_apply_coe,
      -- Set.mem_setOf_eq]
      --use i
      -- apply that s is nonzero in Potion (A,S)
      sorry
     )
    (by
      -- let i ∈ F.index
      -- Then (a) ⊆ (L_i) is trivial, so same holds for image
      -- Reciprocally, we write m=m/a .a.
      sorry)

def Mu_mor_iso (P: Mu L) [DecidableEq P.multicenter.index] :
    A[P.multicenter] ≃ₐ[A] (clo_mu L P).Potion :=
  AlgEquiv.ofBijective _ _
-- lemma Mu_mor_iso (P: Mu L ): Mu_mor is an iso :=
--   by  in


def map_index : fun (P: Mu L)↦ (clo_mu L P : GoodPotionIngredient (ReesAlgebra.intGrading L)) := by
   Mu_rel
   sorry



def BlMu  := Proj (τ := Mu L ) map_index L
    sorry


lemma Dila_cov_proj : BlMu → Bl isIso := by
     --in the paper
    sorry


lemma inter_Po (P P' : Mu L) : ((glueData Proj).map_index P).opensRange ∩
                              ((glueData Proj).map_index P').opensRange
                              = ((glueData Proj).map_index union_Mu P P').opensRange  := by
                  D(S) ∩ D(T) =D(ST)
                  sorry



def (P P': Mu L) : A[P]→ₐ[A] A[union_center P  P'] :=
  desc
  sorry


lemma lemm_dila  [Algebra A B] (P P': Mu L) (c: ι→  nonZeroDivisors B) (i : ι)
(g: A[P]→ₐ[A] B)
(g':  A[P']→ₐ[A] B)
(cond1: Ideal.map (algebraMap A B) (L i) = Ideal.span  {(algebraMap A B) ((c i).1)})
(cond2: (algebraMap A B)= AlgHom.comp g (algebraMap A A[P]) )
(cond2': (algebraMap A B)= AlgHom.comp (g') (algebraMap A A[P'] ) ) :
∃! (g'' : A[union_center P P'] →ₐ[A]B),
   g = AlgHom.comp (g'') (algebraMap A[P] A[union_center P P'])
 ∧  g= AlgHom.comp (g') (algebraMap A[P'] A[union_center P P']) := by
    desc union_center P P'
    sorry



variable {X : Type u} [Scheme X]

structure PreClos where
  indnumb : finite set
  clotop: indnumb → closed (underlying top of X)
  subscheme: indnumb → AlgebraicGeometry.Scheme
  condset : clotop i = underlying top (subscheme i)
  mor: indnumb → subscheme i →sch X
  cov: X.affineCover
  ideal:   indnumb → cov.index → ideal A γ
  condiso: for all i γ  Spec(A_γ/L_iγ)isom[Spec(A_{γ})] mor^{-1} (Spec(A_γ))

/--/
def PreClos_on_refinement (Z: PreClos) (cov': refinment of Z.cov) : X.Preclos :=
   indnumb : Z.indnumb
   clotop: indnumb → closed (underlying top of X)
   subscheme: indnumb → AlgebraicGeometry.Scheme
   condset : clotop i = underlying top (subscheme i)
   mor: indnumb → subscheme i →sch X
   cov: cov'
   ideal:   indnumb → cov.index → image ideal A γ
   condiso: use condiso Z-/


def rel : X.PreClos → X.PreClos → Prop := fun Z Z' =>
   indnumb Z= indnumb Z'
   clotop Z = clotop Z'
   subscheme Z = subscheme Z'
   condset Z = condset Z'
   mor Z = mor Z'

lemma rel_trans

lemma rel_sym

lemma rel_refl

def : Clos = PreClos.quotient

structure PrePri extends PreClos where
  condcar : ideal i γ isPrincipal

structure PreCars extends PrePri where
  condcar : ideal i γ isPrincipalnonZerodiv

structure Pri extends Clos where exist representative in PrePri

structure Cars extends Clos where exists a representative in PreCars


variable {Y: Type u} [Clos X]


def pull_back_Clos(Z: PreClos X) (f: X' → X): X'.PreClos  :=
  indnumb : Z.indnumb
  clotop: indnumb → pullback f oof closed (underlying top of X)
  subscheme: indnumb → pullback f Z.subscheme i
  condset : ok
  mor: pullbackmor
  cov: affine refinement oof pullback X.affineCover
  ideal:   indnumb → cov.index → pullback ideal A γ (not trivial  but can provide very elementary argument )
  condiso: affine routine via pullback and
             AlgebraicGeometry.AffineScheme.equivCommRingCat

lemma pul_back_lem (Z Z': PreClos X) (f: X' → X) (Z rel Z') :  PreClos Z rel PreClos Z' := by
   triviall
   sorry


def pull_back_Clos(Z: Clos X) (f: X' → X): Clos X' :=
    class of PreClos


structure conceptual_blowup (Z: Clos X) where
   scheme: scheme over X
   cond1:  pull_back_Clos Z on scheme is Cartier
   cond2: forr all T → X such that pull_back_Clos is Cartier there exists a unique X-mor T → X



def loc_to_PreClos (L: ι(finite) → ideal A) : PreClos Spec(A):=
   indcov: singleton
   indnumb: ι
   clotop: i ↦ underlying Spec(A/ L i)
   subscheme : i ↦ Spec(A/L i)
   condset: tauto
   mor: i ↦ Spec.hom A → AA/Li
   condcov X =x
   ideal: i ↦ * ↦mapsto L i
   condiso: tauto

def loc_to_Clos (L: ι(finite) → ideal A) : Clos Spec(A):= class of preclos


lemma ProjBlowup_UnivProp_unicity_affine :  (f: T → Spec(A))
     (cond: pullback on T loc_to_clos L is in Cars T)
     (φ φ': T →over Spec(A) BlMu L ): φ=φ'  := by
     Let x ∈ T.
     Reduce to local neighborhood
     put y=φx
     put y'=φ'x
     obtain P ∈ Mu L such that y ∈ Mu P
     obtain p' ∈ Mu L such that y ∈ Mu P'
     Let U=Spec(B) be an affine neighborhood of x in φ^-1 (Po P) ∩ φ'^-1 (Po P').
     consider the restrictions of φ and φ' to U
     Phi factors through Po P, Phi' factors through Po P'
     apply lemma 2
     apply univ prop of dilatations
     sorry

lemma ProjBlowup_UnivProp_existence_affine (f: T → Spec(A))
     (cond: pullback on T loc_to_clos L is in Cars T) : ∃  T →over Spec(A) BlMu L := by
        produce locally some map using dilatation
        glue them using Glue and ProjBlowup_UnivProp_unicity_affine
        sorry

lemma ProjBlowup_UnivProp_affine (f: T → Spec(A))
     (cond: pullback on T loc_to_clos L is in Cars T) :∃!  T →over Spec(A) BlMu L  by
       ProjBlowup_UnivProp_unicity_affine + ProjBlowup_UnivProp_existence_affine
       sorry

lemma dilatation_ring_flat_base_change (χ : A →+* B) (F: Multicenter A):
 χ ∈ RingHom.Flat  : ∃! A[F]⊗[A] B ≅ₐ[B] B[image_mult F] := by
   χ flat and nonzerodiv_image implies that  𝐚^ν is a nonzerodivisor in A[F]⊗[A] B
   cond on ideals is ok
   apply univ property to get a unique B- morphism  <-
   universal property of tensor product, exists ->
   check that both compositions are identity
  sorry

lemma flat_module_localization_at_prime_iff (M: Module.A):
 (M =0) ↔ (∀ q : maxideal.A : localization M A\ q =0 ):=
  → is trivial
  intro M
  assume let x ∈ M let Nx = submodule of M generated by x
  let I=Submodule.annihilator Nx, this is an ideal of A
  ∀ q in maxideal.A, exists f ∈ A \ q such that f∈ I -- because x=0 in the localization
  ∀ q in maxideal.A, I is not included in q
  applying Ideal.exists_le_maximal we get I=A
  so 1.x=0
  so M=0
  sorry

lemma open_implies_flat_ring (χ : A →+* B):
 (B.Spec → A.Spec is open_immerison )→ (χ : A →+* B is flat_ring_map):=
   intro χ
   AlgebraicGeometry.isOpenImmersion_iff_stalk
   and AlgebraicGeometry.IsAffineOpen.isLocalization_stalk implies
   that for all q ⊆ B prime ideals,
   IsLocalization.AtPrime f^-1(q) A → IsLocalization.AtPrime b B
   is an isomorphism
  sorry



lemma base_change_dil_open [Algebra A B]
   (i:Spec(B) → Spec(A) is Open immersion)
   (F: multicenter A) :
   ∃! (Spec(A[F]))×[Spec(A)](Spec(B))≅ Spec(B[image_mult (B:=B) F]) over Spec(B):= by
     exact open_implies_flat_ring  and dilatation_ring_flat_base_change
      sorry

lemma base_change_Bl_open [Algebra A B]
   (i:Spec(B) → Spec(A) is Open immersion)
   (L: ι → ideal A) :
   ∃! (Bl (L))×[Spec(A)](Spec(B))≅ Bl (im L) over Spec(B):=  by
     byy univ prop exists unique φ →
     exists θ <- by fiber product
     φ ∘ θ = id by univ prop
     so θ is injective
     to prove that θ is surjective enough to do it locally on target
     we chose a potion and apply base_change_dil_open
     sorry


def ideal_loc (Z: Clos X) (γ : Z.indcov) : indnumb → ideal A γ :=
   fun i ↦ ideal i γ

def Proj_loc  (Z: Clos X) (γ : Z.indcov) := Bl (ideal_loc Z γ)

def open_pair (Z: Clos X) (γ δ : Z.indcov) := Spec(A_γ) ∩ Spec(A_δ)

def Proj_loc_pair (Z: Clos X) (γ δ : Z.indcov) :=
    inverse image of open_pair in Bl (ideal_loc Z γ)

def Proj_loc_pair_open (Z: Clos X) (γ δ : Z.indcov) (U: open affine of open_pair γ δ) :
   ∃! (inverse image of U inn Proj_loc_pair Z γ δ)  →
   (inverse image of U inn Proj_loc_pair Proj_loc_pair Z δ γ) over U :=
   because it is an iso byy base_change_Bl_open


def Proj_loc_pair_lemm (Z: Clos X) (γ δ : Z.indcov) :
  ∃!   Proj_loc_pair Z γ δ →  Proj_loc_pair Z δ γ such that forr all U, restriction
   to U is given byy Proj_loc_pair_open := by
   because it is an iso byy base_change_Bl_open
   sorry


lemma Proj_loc_pair_iso (Z: Clos X) (γ δ : Z.indcov) :Proj_loc_pair_lemm is Iso :=
   this is local

def BlGlob  (Z: Clos X) :=  Scheme.GlueData where
  J := Clos.indcov
  U γ := Proj_loc γ
  V pair := Proj_loc pair.1 pair.2
  f γ δ := Proj_loc_pair_iso γ δ
  f_id i :=
  f_open i j :=
  t i j :=
  t_id i :=
  t' i j k :=
  t_fac i j k :=
  cocycle i j k :=


lemma ProjBlowup_UnivProp_unicity : (Z: Clos X) (f: T → X)
     (cond: pullback on T oof Z is in Cars T)
     (φ φ': T →over X BlGlob Y): φ=φ'  := by
       use locall
       sorry

lemma ProjBlowup_UnivProp_existence (Z: Clos X) (f: T → X)
     (cond: pullback on T oof Z is in Cars T) : ∃  T →over X BlGlob Y := by
        glue local map
        sorry

lemma ProjBlowup_UnivProp (Z: Clos X) (f: T → X)
     (cond: pullback on T oof Z is in Cars T) : ∃!  T →over X BlGlob Y by
       ProjBlowup_UnivProp_unicity + ProjBlowup_UnivProp_existence
       sorry


-- set_option maxHeartbeats 1000000 in
