import Project.Dilatation.Multicenter
import Mathlib.Data.Sum.Basic
import Project.Dilatation.ReesAlgebra
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.DirectSum.Basic
import Project.Dilatation.lemma
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Localization.Basic
import Project.Dilatation.Family
import Mathlib.RingTheory.GradedAlgebra.Basic
import Mathlib.RingTheory.TensorProduct.Basic
import Project.HomogeneousSubmonoid.Basic
import Project.ForMathlib.TensorProduct
import Project.Proj.Over
import Project.Dilatation.Multicenter

variable {X : Type u} [Scheme X]

structure Clos where
indcov: finite set
indnumb : finite set
clotop: indnumb → closed (underlying top of X)
subscheme: indnumb → AlgebraicGeometry.Scheme
condset : clotop i = underlying top (subscheme i)
mor: indnumb → subscheme i →sch X
condcov: X = finite union over indcov of affine scheme Spec(A γ)
ideal:   indnumb → indcov → ideal A γ
condiso: for all i γ  Spec(A_γ/L_iγ)= mor^{-1} (Spec(A_γ))

structure Cars extends Clos where
nonz: indnumb → indcov → nonZeroDivisors A γ
condcar : ideal i γ = Ideal.span nonz i γ



lemma dilatation_ring_flat_base_change (χ : A →+* B) (F: Multicenter A):
 χ ∈ RingHom.Flat  : ∃! A[F]⊗[A] B ≅ₐ[B] B[image_mult F] := by
   χ flat and nonzerodiv_image implies that  𝐚^ν is a nonzerodivisor in A[F]⊗[A] B
   cond on ideals is ok
   apply univ property to get a unique B- morphism  <-
   universal property of tensor product, exists ->
   check that both compositions are identity
  sorry

lemma flat_module_localization_at_prime_iff (M: Module.A):
 (M =0) ↔ (∀ q : maxideal.A : localization M A\ q =0 ):=
  → is trivial
  intro M
  assume let x ∈ M let Nx = submodule of M generated by x
  let I=Submodule.annihilator Nx, this is an ideal of A
  ∀ q in maxideal.A, exists f ∈ A \ q such that f∈ I -- because x=0 in the localization
  ∀ q in maxideal.A, I is not included in q
  applying Ideal.exists_le_maximal we get I=A
  so 1.x=0
  so M=0
  sorry

lemma open_implies_flat_ring (χ : A →+* B):
 (B.Spec → A.Spec is open_immerison )→ (χ : A →+* B is flat_ring_map):=
   intro χ
   AlgebraicGeometry.isOpenImmersion_iff_stalk
   and AlgebraicGeometry.IsAffineOpen.isLocalization_stalk implies
   that for all q ⊆ B prime ideals,
   IsLocalization.AtPrime f^-1(q) A → IsLocalization.AtPrime b B
   is an isomorphism
  sorry



lemma base_change_dil_open [Algebra A B]
   (i:Spec(B) → Spec(A) is Open immersion)
   (F: multicenter A) :
   ∃! (Spec(A[F]))×[Spec(A)](Spec(B))≅ Spec(B[image_mult (B:=B) F]) over Spec(B):= by
     exact open_implies_flat_ring  and dilatation_ring_flat_base_change
      sorry

lemma base_change_Bl_open [Algebra A B]
   (i:Spec(B) → Spec(A) is Open immersion)
   (L: ι → ideal A) :
   ∃! (Bl (L))×[Spec(A)](Spec(B))≅ Bl (im L) over Spec(B):=  by
     byy univ prop exists unique φ →
     exists θ <- by fiber product
     φ ∘ θ = id by univ prop
     so θ is injective
     to prove that θ is surjective enough to do it locally on target
     we chose a potion and apply base_change_dil_open
     sorry


def ideal_loc (Z: Clos X) (γ : Z.indcov) : indnumb → ideal A γ :=
   fun i ↦ ideal i γ

def Proj_loc  (Z: Clos X) (γ : Z.indcov) := Bl (ideal_loc Z γ)

def open_pair (Z: Clos X) (γ δ : Z.indcov) := Spec(A_γ) ∩ Spec(A_δ)

def Proj_loc_pair (Z: Clos X) (γ δ : Z.indcov) :=
    inverse image of open_pair in Bl (ideal_loc Z γ)

def Proj_loc_pair_open (Z: Clos X) (γ δ : Z.indcov) (U: open affine of open_pair γ δ) :
   ∃! (inverse image of U inn Proj_loc_pair Z γ δ)  →
   (inverse image of U inn Proj_loc_pair Proj_loc_pair Z δ γ) over U :=
   because it is an iso byy base_change_Bl_open


def Proj_loc_pair_lemm (Z: Clos X) (γ δ : Z.indcov) :
  ∃!   Proj_loc_pair Z γ δ →  Proj_loc_pair Z δ γ such that forr all U, restriction
   to U is given byy Proj_loc_pair_open := by
   because it is an iso byy base_change_Bl_open
   sorry


lemma Proj_loc_pair_iso (Z: Clos X) (γ δ : Z.indcov) :Proj_loc_pair_lemm is Iso :=
   this is local

def BlGlob  (Z: Clos X) :=  Scheme.GlueData where
  J := Clos.indcov
  U γ := Proj_loc γ
  V pair := Proj_loc pair.1 pair.2
  f γ δ := Proj_loc_pair_iso
  f_id i :=
  f_open i j :=
  t i j :=
  t_id i :=
  t' i j k :=
  t_fac i j k :=
  cocycle i j k :=

-- set_option maxHeartbeats 1000000 in
